server:
  port: 8083


mybatis:
  type-aliases-package: com.wage.bean
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/finace?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  thymeleaf:
    cache: true
#  dubbo:
#    application:
#      name: provider
#    registry:
#      address: zookeeper://127.0.0.1:2181
#    protocol:
#      name: dubbo
#      port: 20880
#    scan: com.commom.dubbo

